### ISSUE TITLE
Asking for documentation

### ISSUE THREAD

**Issue by FernandoLpz** [jakee/frequent-subgraph-patterns#1]
Hi @jakee 
I have taken a look at your implementation, I would like to know if you have any available documentation about this model.
Thanks!

**Comment by jakee** [comment]
Hi! The article "Mining Frequent Patterns in Evolving Graphs" explains the algorithms this model is based on. You can find it here: https://arxiv.org/abs/1809.00394

**Comment by FernandoLpz** [comment]
Thanks!
